### ISSUE TITLE
Remove incomprehinsible config system

### ISSUE THREAD

**Issue by MechaFinch** [cadet-robotics/2019_repo#10]
As the new config system provides little to no advantage and adds illegible, unnecessary, and _uncommented_ code, which most importantly makes the system very difficult for most people to understand, it needs to be reverted to its original intentions.  
The final version of the config system should be essentially the old version of the config system, but reorganized to be in the constructors of the classes rather than the `init()` method as in the old systems.  
No new systems should be added compared to the old config system, it should only have been a reorganization.  
The so-described "null returning functions" should not be necessary, as they are both a new system and reduce debugging ability should be config be corrupted in some way (the only reason the conversion functions would error).

**Comment by 21oavery** [comment]
#12 This should improve how error code works. I also added comments

**Comment by MechaFinch** [comment]
#13 Should be a good compromise. Includes a replacement exception, ConfigException, a small ConfigUtil class including 2 methods, isFiltered and getAsInt, which reduce repetition significantly, and finally it moves the init call into the constructor.
